language: python
python:
  - "3.6"

before_install:
  # For building wheel for pyaudio on Ubuntu 16.04
  - sudo apt-get -qq update
  - sudo apt-get install -y -f python-pyaudio libportaudio2 libasound-dev portaudio19-dev libportaudiocpp0
  - python -m pip install --upgrade setuptools pip virtualenv
 
# command to install dependencies
install:
  - pip install -r requirements-test.txt

# command to run tests
script: py.test
