language: python
python:
  - "2.7"
  - "3.4"

"before_install": [
  "python -m pip install --upgrade setuptools pip virtualenv"
]
# command to install dependencies
install: [
  "pip install -r requirements-test.txt"
]
# command to run tests
script: py.test